### 경북대학교 전기가스 사용량 API 조회

In [2]:
import requests
import json

url = 'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo?sigunguCd=11680&bjdongCd=10300&bun=0012&ji=0000&useYm=201501&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'

# <response>
# <header>
# <resultCode>00</resultCode>
# <resultMsg>NORMAL SERVICE.</resultMsg>
# </header>
# <body>
# <items>
# <item>
# <bjdongCd>10300</bjdongCd>
# <bun>0012</bun>
# <ji>0000</ji>
# <naMainBun>21.0</naMainBun>
# <naRoadCd>116804166040</naRoadCd>
# <naSubBun>0.0</naSubBun>
# <naUgrndCd>0</naUgrndCd>
# <newPlatPlc>서울특별시 강남구 개포로109길 21</newPlatPlc>
# <platGbCd>0</platGbCd>
# <platPlc>서울특별시 강남구 개포동 12번지</platPlc>
# <rnum>1</rnum>
# <sigunguCd>11680</sigunguCd>
# <useQty>1112466.0</useQty>
# <useYm>201501</useYm>
# </item>
# </items>
# <numOfRows>10</numOfRows>
# <pageNo>1</pageNo>
# <totalCount>1</totalCount>
# </body>
# </response>

# newPlatPlc = '대구광역시 북구 대학로 80' 인 데이터 조회

response = requests.get(url)
data = response.text
print(data)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><bjdongCd>10300</bjdongCd><bun>0012</bun><ji>0000</ji><naMainBun>21.0</naMainBun><naRoadCd>116804166040</naRoadCd><naSubBun>0.0</naSubBun><naUgrndCd>0</naUgrndCd><newPlatPlc>서울특별시 강남구 개포로109길 21</newPlatPlc><platGbCd>0</platGbCd><platPlc>서울특별시 강남구 개포동 12번지</platPlc><rnum>1</rnum><sigunguCd>11680</sigunguCd><useQty>1112466.0</useQty><useYm>201501</useYm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>1</totalCount></body></response>

In [3]:
# 경북대학교 정보
# sigunguCd = 27230
# bjdongCd = 11100
# bun = 1370
# ji = 0001
# useYm = 202401
# numOfRows = 10
# pageNo = 1

# useYm 을 201101 ~ 202402 까지 조회
for year in range(2011, 2024):
    for month in range(1, 13):
        useYm = f'{year}{month:02d}'
        url = f'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo?sigunguCd=27230&bjdongCd=11100&bun=1370&ji=0001&useYm={useYm}&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'
        response = requests.get(url)
        data = response.text
        print(data)
        break
    break

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><bjdongCd>11100</bjdongCd><bun>1370</bun><ji>0001</ji><naMainBun>80.0</naMainBun><naRoadCd>272303145021</naRoadCd><naSubBun>0.0</naSubBun><naUgrndCd>0</naUgrndCd><newPlatPlc>대구광역시 북구 대학로 80</newPlatPlc><platGbCd>0</platGbCd><platPlc>대구광역시 북구 산격동 1370-1번지</platPlc><rnum>1</rnum><sigunguCd>27230</sigunguCd><useQty>194.0</useQty><useYm>201101</useYm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>1</totalCount></body></response>

In [11]:
import xml.etree.ElementTree as ET
root = ET.fromstring(data)
print(root.tag)
print(root.attrib)
for child in root:
    print(child.tag, child.attrib)
    
for item in root.iter('item'):
    print(item.tag)
    for child in item:
        print(child.tag, child.text)

response
{}
header {}
body {}
item
bjdongCd 11100
bun 1370
ji 0001
naMainBun 80.0
naRoadCd 272303145021
naSubBun 0.0
naUgrndCd 0
newPlatPlc 대구광역시 북구 대학로 80
platGbCd 0
platPlc 대구광역시 북구 산격동 1370-1번지
rnum 1
sigunguCd 27230
useQty 194.0
useYm 201101

In [12]:
# useQty를 출력
for item in root.iter('item'):
    for child in item:
        if child.tag == 'useQty':
            print(child.text)

194.0

In [19]:
# 종합
import pandas as pd

df = pd.DataFrame(columns=['useYm', 'useQty'])

for year in range(2011, 2024):
    for month in range(1, 13):
        useYm = f'{year}{month:02d}'
        url = f'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo?sigunguCd=27230&bjdongCd=11100&bun=1370&ji=0001&useYm={useYm}&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'
        response = requests.get(url)
        data = response.text
        root = ET.fromstring(data)
        for item in root.iter('item'):
            for child in item:
                if child.tag == 'useQty':
                    print(useYm, child.text)
                    df = df.concat(pd.DataFrame({'useYm': [useYm], 'useQty': [child.text]}))
        break

df

201101 194.0

AttributeError: 'DataFrame' object has no attribute 'concat'

In [ ]:
new_data = pd.DataFrame({'useYm': ['202201', '202202'], 'useQty': [100, 200]})
df = pd.concat([df, new_data], ignore_index=True)

In [21]:
import pandas as pd
import requests
import xml.etree.ElementTree as ET

df = pd.DataFrame(columns=['useYm', 'useQty'])

for year in range(2011, 2024):
    for month in range(1, 13):
        useYm = f'{year}{month:02d}'
        url = f'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo?sigunguCd=27230&bjdongCd=11100&bun=1370&ji=0001&useYm={useYm}&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'
        response = requests.get(url)
        data = response.text
        root = ET.fromstring(data)
        for item in root.iter('item'):
            for child in item:
                if child.tag == 'useQty':
                    print(useYm, child.text)
                    new_row = pd.DataFrame({'useYm': [useYm], 'useQty': [child.text]})
                    df = pd.concat([df, new_row], ignore_index=True)

print(df)

201101 194.0
201102 188.0
201103 267.0
201104 289.0
201105 284.0
201106 1003.0
201107 1054.0
201108 450.0
201109 448.0
201110 385.0
201111 420.0
201112 396.0
201201 320.0
201202 287.0
201203 372.0
201204 390.0
201205 386.0
201206 438.0
201207 379.0
201208 367.0
201209 796.0
201210 1059.0
201211 572.0
201212 456.0
201301 377.0
201302 210.0
201303 269.0
201304 352.0
201305 352.0
201306 461.0
201307 465.0
201308 449.0
201309 462.0
201310 367.0
201311 341.0
201312 305.0
201401 216.0
201402 128.0
201403 300.0
201404 340.0
201405 351.0
201406 285.0
201407 596.0
201408 1.0
201409 455.0
201410 484.0
201411 426.0
201412 439.0
201501 402.0
201502 351.0
201503 401.0
201504 490.0
201505 432.0
201506 424.0
201507 423.0
201508 363.0
201509 387.0
201510 447.0
201511 437.0
201512 456.0
201601 408.0
201602 372.0
201603 430.0
201604 471.0
201605 491.0
201606 541.0
201703 518.0
201704 515.0
201705 542.0
201706 614.0
201707 537.0
201708 557.0
201709 4913.0
201710 5785.0
201711 15349.0
201712 35420.0
201801 44546.0
201802 52017.0
201803 32102.0
201804 20432.0
201805 9902.0
201806 11581.0
201807 9365.0
201808 14005.0
201809 14280.0
201810 14015.0
201811 24726.0
201812 41943.0
201901 50085.0
201902 37185.0
201903 24458.0
201904 22283.0
201905 11798.0
201906 4635.0
201907 5146.0
201908 6083.0
201909 5994.0
201910 4270.0
201911 6889.0
201912 10990.0
202001 11821.0
202002 10808.0
202003 10774.0
202004 112331.0
202005 108627.0
202006 107926.0
202007 130267.0
202008 124386.0
202011 129006.0
202012 156247.0
202101 178661.0
202102 168657.0
202103 127284.0
202104 177906.0
202105 151263.0
202106 151278.0
202107 158952.0
202108 165521.0
202109 167524.0
202110 157057.0
202111 159203.0
202112 162964.0
202201 191391.0
202202 160922.0
202203 132289.0
202204 174460.0
202205 135723.0
202206 146926.0
202207 170461.0
202208 180289.0
202209 169151.0
202210 156861.0
202211 138406.0
202212 148996.0
202301 189248.0
202302 154699.0
202303 119090.0
202304 155122.0
202305 129896.0
202306 140844.0
202307 164994.0
202308 167263.0
202309 182880.0
202310 175957.0
202311 130124.0
202312 149871.0
      useYm    useQty
0    201101     194.0
1    201102     188.0
2    201103     267.0
3    201104     289.0
4    201105     284.0
..      ...       ...
141  202308  167263.0
142  202309  182880.0
143  202310  175957.0
144  202311  130124.0
145  202312  149871.0

[146 rows x 2 columns]

In [22]:
# 202401, 202402 데이터를 조회하여 DataFrame에 추가
for month in range(1, 3):
    useYm = f'2024{month:02d}'
    url = f'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo?sigunguCd=27230&bjdongCd=11100&bun=1370&ji=0001&useYm={useYm}&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'
    response = requests.get(url)
    data = response.text
    root = ET.fromstring(data)
    for item in root.iter('item'):
        for child in item:
            if child.tag == 'useQty':
                print(useYm, child.text)
                new_row = pd.DataFrame({'useYm': [useYm], 'useQty': [child.text]})
                df = pd.concat([df, new_row], ignore_index=True)

print(df)

202401 172577.0
202402 141258.0
      useYm    useQty
0    201101     194.0
1    201102     188.0
2    201103     267.0
3    201104     289.0
4    201105     284.0
..      ...       ...
143  202310  175957.0
144  202311  130124.0
145  202312  149871.0
146  202401  172577.0
147  202402  141258.0

[148 rows x 2 columns]

In [25]:
df.to_csv('DATA/elec_data.csv', index=False)

In [26]:
# 이제 가스 데이터 조회
# example url = 'http://apis.data.go.kr/1611000/BldEngyService/getBeGasUsgInfo?sigunguCd=11680&bjdongCd=10300&bun=0012&ji=0000&useYm=201501&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'

df = pd.DataFrame(columns=['useYm', 'useQty'])

for year in range(2011, 2025):
    if year == 2024:
        end_month = 3
    else:
        end_month = 13
    for month in range(1, end_month):
        useYm = f'{year}{month:02d}'
        url = f'http://apis.data.go.kr/1611000/BldEngyService/getBeGasUsgInfo?sigunguCd=27230&bjdongCd=11100&bun=1370&ji=0001&useYm={useYm}&ServiceKey=HcemfTODn25HOfvMHgFXSX%2BwwiGPX7McdKfXb09VzlvlBo3vmSQcwOx0oybt2SYSTUMa0TdDoe1nIOy7MeYdbg%3D%3D'
        response = requests.get(url)
        data = response.text
        root = ET.fromstring(data)
        for item in root.iter('item'):
            for child in item:
                if child.tag == 'useQty':
                    print(useYm, child.text)
                    new_row = pd.DataFrame({'useYm': [useYm], 'useQty': [child.text]})
                    df = pd.concat([df, new_row], ignore_index=True)
                    
print(df)

201101 9168269.0
201102 7072076.0
201103 5656101.0
201104 4096409.0
201105 1862692.0
201106 1848097.0
201107 2767573.0
201108 2996325.0
201109 2598040.0
201110 1595558.0
201111 2087381.0
201112 5869632.0
201201 7709910.0
201202 7138629.0
201203 5537778.0
201204 3784383.0
201205 1563247.0
201206 1827096.0
201207 2057420.0
201208 2900647.0
201209 2509299.0
201210 1055575.0
201211 2037064.0
201212 6120959.0
201301 7412747.0
201302 6580732.0
201303 4989257.0
201304 3458037.0
201305 1777585.0
201306 1681673.0
201307 2422026.0
201308 2985752.0
201309 2336134.0
201310 1171135.0
201311 2100472.0
201312 5249648.0
201401 7189593.0
201402 6211391.0
201403 5121662.0
201404 2331079.0
201405 1499564.0
201406 1733628.0
201407 2379462.0
201408 2543238.0
201409 1788229.0
201410 1348592.0
201411 2344313.0
201412 5885367.0
201501 6890625.0
201502 6488253.0
201503 5455795.0
201504 2968338.0
201505 1675397.0
201506 1847324.0
201507 2097332.0
201508 2747260.0
201509 2243280.0
201510 1320289.0
201511 2029769.0
201512 4645810.0
201601 6365484.0
201602 6410824.0
201603 5178591.0
201604 2879700.0
201605 1407800.0
201606 2063776.0
201607 280245.0
201608 183226.0
201609 236505.0
201610 360956.0
201611 571312.0
201612 891207.0
201701 1019494.0
201702 1044104.0
201703 4662477.0
201704 3544541.0
201705 1299722.0
201706 2041420.0
201707 2672402.0
201708 2685199.0
201709 2572871.0
201710 1291931.0
201711 1795473.0
201712 6441111.0
201801 6433176.0
201802 7137334.0
201803 4624452.0
201804 3314976.0
201805 1515016.0
201806 2078352.0
201807 2284945.0
201808 3207913.0
201809 2523051.0
201810 1263741.0
201811 2041455.0
201812 5384958.0
201901 6203082.0
201902 6135890.0
201903 4143415.0
201904 2949015.0
201905 1543731.0
201906 1922570.0
201907 2170339.0
201908 2847339.0
201909 2402251.0
201910 1676735.0
201911 2243552.0
202001 5577262.0
202002 5173927.0
202003 3260645.0
202004 1073557.0
202005 400349.0
202006 984664.0
202007 1835487.0
202008 1963460.0
202011 1611151.0
202012 4563120.0
202101 5881385.0
202102 5301263.0
202103 3770043.0
202104 2312270.0
202105 1024338.0
202106 1468242.0
202107 1916343.0
202108 2202817.0
202109 1846366.0
202110 1274519.0
202111 1186632.0
202112 3549872.0
202201 4953142.0
202202 4469127.0
202203 3311979.0
202204 1955787.0
202205 804121.0
202206 1398516.0
202207 2332518.0
202208 2127562.0
202209 1790982.0
202210 1332163.0
202211 1353364.0
202212 3706359.0
202301 5163283.0
202302 4951988.0
202303 3050170.0
202304 1782191.0
202305 983409.0
202306 1708440.0
202307 2188141.0
202308 2307551.0
202309 2529407.0
202310 1214706.0
202311 1440307.0
202312 3956066.0
202401 3910183.0
202402 3711023.0
      useYm     useQty
0    201101  9168269.0
1    201102  7072076.0
2    201103  5656101.0
3    201104  4096409.0
4    201105  1862692.0
..      ...        ...
150  202310  1214706.0
151  202311  1440307.0
152  202312  3956066.0
153  202401  3910183.0
154  202402  3711023.0

[155 rows x 2 columns]

In [27]:
df.to_csv('DATA/gas_data.csv', index=False)